# This is a basic workflow to help you get started with Actions

name: android_staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types:
      - prereleased
  workflow_dispatch:
    inputs:
      proxyURL:
        description: 'Charles Proxy URL'
        default: ''
      appBundle:
        description: 'Enable app bundle'
        default: 'false'
#on:
#  push:
#    branches: [continuous-integration/NXT-3479-update-fastlane-configuration-2]
#  pull_request:
#    branches: [continuous-integration/NXT-3479-update-fastlane-configuration-2]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_android:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: false
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ secrets.FLUTTER_VERSION }} # 2.5.2
          channel: ${{ secrets.FLUTTER_CHANNEL }} # stable
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'continuous_integration_staging'
          subdirectory: 'android'
          options: '{ "last_tag": "${{github.event.commits[0].sha}}", "last_commit_message": "${{github.event.commits[0].message}}", "proxy_url": "${{github.event.inputs.proxyURL}}", "is_app_bundle": "${{github.event.inputs.appBundle}}" }'
        env:
          FASTLANE_CUSTOMERAPP_APIKEY: ${{ secrets.FASTLANE_CUSTOMERAPP_APIKEY }}
          SDK_REGISTRY_TOKEN: ${{ secrets.SDK_REGISTRY_TOKEN }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
          ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          SLACK_UPLOAD_CHANNEL: ${{ secrets.SLACK_UPLOAD_CHANNEL }}
          APP_CONFIGS: ${{ secrets.APP_CONFIGS }}
          STAGING_KEYSTORE_BASE64: ${{ secrets.STAGING_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_STAGING_ALIAS: ${{ secrets.ANDROID_KEYSTORE_STAGING_ALIAS }}
          CI: true
