name: android_build

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build_android:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:


      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: false
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.0' # 2.5.2
          channel: 'stable' # stable
      - uses: actions/checkout@v2
      - run: flutter pub get
      - run: flutter build apk --target-platform android-arm64
