name: android_build

on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build_android:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          check-latest: false
      - uses: android-actions/setup-android@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.0' # 2.5.2
          channel: 'stable' # stable
          cache: true
      - uses: actions/checkout@v2
      - run: flutter pub get
      - run: flutter doctor -v
      - run: flutter build apk --target-platform android-arm64

      - uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C04BAVAPS0P,C04BJTPAJEA'
          slack-message: "Apk build result: ${{ job.status }}\n"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
